#+TITLE: Working with the Heltec WiFi LoRa 32 (V3) module

* Table of Contents :TOC:
- [[#introduction][Introduction]]
- [[#heltec-wifi-lora-32-v3][Heltec WiFi LoRa 32 (V3)]]
  - [[#other-assessories][Other Assessories]]

* Introduction
The following is mostly taken from the Heltec Automation webpage on the WiFi
LoRa 32 (V3) developer board, but with ‘fixes’. For definitive details, please
refer to the original web page. (Changes have been made to improve readability
and add details useful for developers.)

This board is planned to be included in a major hardware project, and this
information will assist with development and maintenance.

This information was initially hosted on a page at [[mawsonlakes.org][MawsonLakes.Org]] (WorkPress),
but it has been moved to a github repository to allow better development
workflow based access.

* Heltec WiFi LoRa 32 (V3)

- Price : $18.90 (from Heltec, Jan 2023)
- What's in the Package

  Included
  - Antenna
  - SH1.25 x 2 battery connector
  - 2 x 54 pin headers (not soldered by default),

  Not included
  - Battery
  - Package Notes

When purchased with the shell, the pin headers are soldered underneath the
board. The glue stick antenna is too long to fit inside the shell, and will be
connected but outside of the enclosure.

- LoRa Bands : 470-510MHz, 863-870MHz, *902-928MHz* (band in use)

** Other Assessories
- Battery: 3.7V/1000mAh Lithium (Sale only available inside mainland China)
- Cooling rib
- Antenna
- Bread Board
- Plastic shell

Categories: ESP Arduino, LoRa Node SKU: ZC-153-868-1

Tags: ArduinoESP32LoRa NodeLoRaWAN

The WiFi LoRa 32 (V3) is a classic IoT dev-board designed & produced by Heltec
Automation. Since its launch in 2017, it has been loved by developers and
makers. The newly launched V3 version has the same pin sequence as the V2
version and retains Wi-Fi, BLE, LoRa, and the OLED display.

This board is the best option for smart cities, farms, homes, industrial
control, house security, wireless meter reading, and IoT developers.
